# Workflow that is used in other repos to check the copyright headers
name: Check copyright headers

on:
  workflow_call:
    inputs:
      header-to-check:
        description: 'Contains the template of the header to be checked for'
        default: "Copyright (c) The OpenTofu Authors\nSPDX-License-Identifier: MPL-2.0\nCopyright (c) 2023 HashiCorp, Inc.\nSPDX-License-Identifier: MPL-2.0"
        type: string
      search-patterns:
        description: 'The pattern to be used when scaning for files to be checked'
        default: '"**/*.go" "**/*.proto"'
        type: string
      ignore-flags:
        description: 'A list of -s (--skip) flags to be used when specific paths should be excluded'
        default: '-s ".git/**/*"'
        type: string

jobs:
  copyright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Validate Header Compliance
        run: |
          set -e
          curl -sSfL https://github.com/B1NARY-GR0UP/nwa/releases/download/v0.8.0/nwa_Linux_x86_64.tar.gz | tar -xzf - -C /usr/local/bin nwa
          
          _copyright_header_templ_file="copyright_header_template"
          echo "${{ inputs.header-to-check }}" > "${_copyright_header_templ_file}" 
          if ! nwa check -f -T static --tmpl "${_copyright_header_templ_file}" ${{ inputs.ignore-flags }} ${{ inputs.search-patterns }} ; then
            echo >&2 "ERROR: some files are missing required copyright headers"
            exit 1
          fi
          exit 0
        shell: bash
